version: 2

sources:
  - name: base_data
    database: SANDBOX
    schema: SHOPKINS
    tables:
      - name: customers
      - name: order_details
      - name: categories
      - name: employees
      - name: employee_territories
      - name: orders
      - name: products
      - name: regions
      - name: shippers
      - name: suppliers
      - name: territories

